---
kind: Service
apiVersion: v1
metadata:
  name: http-lb
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
spec:
  type: LoadBalancer
  selector:
    app: external
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: "80-port"
    - name: myapp
      protocol: TCP
      port: 5173
      targetPort: "5173-port"